language: node_js
node_js:
  - 12
services: mongodb
before_install:
  - cd ${TRAVIS_BUILD_DIR}/backend/src/config
  - openssl aes-256-cbc -K $encrypted_35c8e4cc1596_key -iv $encrypted_35c8e4cc1596_iv -in fbServiceAccountKey.json.enc -out fbServiceAccountKey.json -d
before_script:
  - cd ${TRAVIS_BUILD_DIR}/backend
  - npm install
script:
  - npm run lint
  - npm test
